# Use root/secret-password as user/password credentials
services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: craftedby_db
      MARIADB_USER: crafted_admin
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: secret-password
    ports:
      - "3306:3306"
    networks:
      - common_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - common_network

  app:
    image: adrewkirts/crafted-by_backend
    ports:
      - "8000:80"

    networks:
      - common_network

networks:
  common_network:
    external: true