# Use root/secret-password as user/password credentials
services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: craftedby_db
      MARIADB_USER: crafted_admin
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: secret-password
    ports:
      - "3306:3306"
    networks:
      - common_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - common_network

  backend:
    image: adrewkirts/crafted-by_backend
    restart: always
    container_name: craftedby-backend
    ports:
      - "8000:80"
    networks:
      - common_network

  frontend:
    image: adrewkirts/crafted-by_frontend
    restart: always
    container_name: craftedby-frontend
    ports:
      - "8081:80"

networks:
  common_network:
    external: true